services:
  - docker

before_install:
  - ssh-keygen -f /tmp/id_rsa -P '' -t rsa

install:
  - docker build -t sshsocks .
  - docker run -d -p 127.0.0.1:2222:2222 --security-opt no-new-privileges --cap-drop ALL -v /tmp/id_rsa.pub:/proxy/authorized_keys:ro --add-host example.com:192.30.253.112 --name sshsocks sshsocks

before_script:
  - ssh -N -f -p 2222 -D 8822 -i /tmp/id_rsa proxy@localhost -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

script:
  - docker ps --format {{.Names}} | grep -q sshsocks
  - curl -s -k -I --socks5-hostname 127.0.0.1:8822 https://example.com | grep -q Location:\ https://github.com/
